-- Create metrics_history table
CREATE TABLE IF NOT EXISTS public.metrics_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    influencer_id BIGINT REFERENCES public.influencers(id) ON DELETE CASCADE,
    followers INTEGER,
    following INTEGER,
    total_posts INTEGER,
    average_likes INTEGER,
    average_comments INTEGER,
    reel_views INTEGER,
    capture_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security
ALTER TABLE public.metrics_history ENABLE ROW LEVEL SECURITY;

-- Create policies (Allowing public access for now as per project context)
CREATE POLICY "Enable read access for all users" ON public.metrics_history FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users" ON public.metrics_history FOR INSERT WITH CHECK (true);
