-- Create subcategories table
CREATE TABLE IF NOT EXISTS public.subcategories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT REFERENCES public.categories(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(category_id, name)
);

-- Enable Row Level Security
ALTER TABLE public.subcategories ENABLE ROW LEVEL SECURITY;

-- Create policies (Allowing public access for now as per project context)
CREATE POLICY "Enable read access for all users" ON public.subcategories FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users" ON public.subcategories FOR INSERT WITH CHECK (true);

-- Insert default subcategories for 'Coding'
-- We use a subquery to find 'Coding' category ID
DO $$
DECLARE
    coding_id BIGINT;
BEGIN
    SELECT id INTO coding_id FROM public.categories WHERE name = 'Coding';
    
    IF coding_id IS NOT NULL THEN
        INSERT INTO public.subcategories (category_id, name)
        VALUES 
            (coding_id, 'Web Development'),
            (coding_id, 'Software Development'),
            (coding_id, 'Data Science'),
            (coding_id, 'Frontend Development'),
            (coding_id, 'Backend Development')
        ON CONFLICT (category_id, name) DO NOTHING;
    END IF;
END $$;
