-- Create reels table
-- This migration provides the base structure required by the application
-- and subsequent alignment migrations.

CREATE TABLE IF NOT EXISTS public.reels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    influencer_id BIGINT REFERENCES public.influencers(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    reel_url TEXT NOT NULL UNIQUE,
    video_url TEXT,
    display_url TEXT,
    likes INTEGER DEFAULT 0,
    views BIGINT DEFAULT 0,
    posted_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Enable Row Level Security
ALTER TABLE public.reels ENABLE ROW LEVEL SECURITY;

-- Create basic policies (democratized access for now as per current project architecture)
DROP POLICY IF EXISTS "Enable read access for all users" ON public.reels;
CREATE POLICY "Enable read access for all users" ON public.reels FOR SELECT USING (true);

DROP POLICY IF EXISTS "Enable insert access for all users" ON public.reels;
CREATE POLICY "Enable insert access for all users" ON public.reels FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Enable update access for all users" ON public.reels;
CREATE POLICY "Enable update access for all users" ON public.reels FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Enable delete access for all users" ON public.reels;
CREATE POLICY "Enable delete access for all users" ON public.reels FOR DELETE USING (true);
