-- Create influencers table
CREATE TABLE IF NOT EXISTS public.influencers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    profile_url TEXT NOT NULL,
    category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
    subcategory_id BIGINT REFERENCES public.subcategories(id) ON DELETE SET NULL,
    added_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security
ALTER TABLE public.influencers ENABLE ROW LEVEL SECURITY;

-- Create policies (Allowing public access for now as per project context)
CREATE POLICY "Enable read access for all users" ON public.influencers FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users" ON public.influencers FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update access for all users" ON public.influencers FOR UPDATE USING (true);
CREATE POLICY "Enable delete access for all users" ON public.influencers FOR DELETE USING (true);
