-- Create post_insta_data table to store all post data in JSON format
CREATE TABLE IF NOT EXISTS post_insta_data (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL,
  post_data JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security
ALTER TABLE post_insta_data ENABLE ROW LEVEL SECURITY;

-- Allow anonymous selects for demo/frontend display
DROP POLICY IF EXISTS "Allow anonymous post reads" ON post_insta_data;
CREATE POLICY "Allow anonymous post reads" ON post_insta_data
  FOR SELECT USING (true);

-- Allow service role to perform any action (used by Edge Functions)
DROP POLICY IF EXISTS "Service role full access" ON post_insta_data;
CREATE POLICY "Service role full access" ON post_insta_data
  USING (auth.jwt() ->> 'role' = 'service_role');
