-- Create influencers table
-- This migration provides the base structure for influencers
-- including the now-core user_id for isolation.

CREATE TABLE IF NOT EXISTS public.influencers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    profile_url TEXT NOT NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
    subcategory_id BIGINT REFERENCES public.subcategories(id) ON DELETE SET NULL,
    added_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security
ALTER TABLE public.influencers ENABLE ROW LEVEL SECURITY;

-- Idempotent Policy Creation
-- We drop existing policies before creating them to avoid "Already Exists" errors
DROP POLICY IF EXISTS "Enable read access for all users" ON public.influencers;
CREATE POLICY "Enable read access for all users" ON public.influencers FOR SELECT USING (true);

DROP POLICY IF EXISTS "Enable insert access for all users" ON public.influencers;
CREATE POLICY "Enable insert access for all users" ON public.influencers FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Enable update access for all users" ON public.influencers;
CREATE POLICY "Enable update access for all users" ON public.influencers FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Enable delete access for all users" ON public.influencers;
CREATE POLICY "Enable delete access for all users" ON public.influencers FOR DELETE USING (true);
