-- Create categories table
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

-- Create policies (Allowing public access for now as per project context)
CREATE POLICY "Enable read access for all users" ON public.categories FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users" ON public.categories FOR INSERT WITH CHECK (true);

-- Insert default categories
INSERT INTO public.categories (name)
VALUES 
    ('Coding'),
    ('AI Tools'),
    ('Design'),
    ('EdTech'),
    ('Others')
ON CONFLICT (name) DO NOTHING;
