-- Create instagram_profile_data table
CREATE TABLE IF NOT EXISTS instagram_profile_data (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category TEXT,
  instagram_profile_id TEXT,
  instagram_link TEXT,
  views BIGINT,
  likes BIGINT,
  shares BIGINT,
  comments BIGINT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security
ALTER TABLE instagram_profile_data ENABLE ROW LEVEL SECURITY;

-- Create policy to allow anonymous inserts (for development/demo)
DROP POLICY IF EXISTS "Allow anonymous inserts" ON instagram_profile_data;
CREATE POLICY "Allow anonymous inserts" ON instagram_profile_data
  FOR INSERT WITH CHECK (true);

-- Create policy to allow anonymous reads (for development/demo)
DROP POLICY IF EXISTS "Allow anonymous reads" ON instagram_profile_data;
CREATE POLICY "Allow anonymous reads" ON instagram_profile_data
  FOR SELECT USING (true);

-- Add sample seed data
INSERT INTO instagram_profile_data (category, instagram_profile_id, instagram_link, views, likes, shares, comments)
VALUES 
('Frontend Technologies', 'nike', 'https://www.instagram.com/nike/', 1500000, 45000, 1200, 800),
('Frontend Technologies', 'adidas', 'https://www.instagram.com/adidas/', 1200000, 38000, 1000, 600);
